plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true