language: ruby
os: linux
dist: bionic
cache: bundler
services:
  - postgresql
  - xvfb
addons:
  chrome: stable
before_install:
  - gem install bundler
  - sed -i 's/x64-mingw32//g' Gemfile.lock
before_script:
  - psql -c 'CREATE DATABASE stacktask_test;' -U postgres
  - rake db:migrate
  - rake webpacker:install
deploy:
  provider: heroku
  edge: true
  app: stacktask
  strategy: api
  run: rake db:migrate
  on:
    branch: master