language: ruby
os: linux
dist: bionic
cache: bundler
services:
  - postgresql
before_install:
  - gem install bundler
before_script:
  - psql -c 'CREATE DATABASE stacktask_test;' -U postgres
  - rails db:migrate
deploy:
  provider: heroku
  edge: true
  app: stacktask
  strategy: api
  run: rails db:migrate
  on:
    branch: master